#!url=https://vantuan2703/module/usage.module
#!name=Usage💤.mudule
#!desc= By: ѵăռŧυấռ 💤
#!homepage=https://vantuan2703
#!author= 89996462
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/usage.png

[MITM]
hostname = %APPEND% api.revenuecat.com

[Script]
Usage=type=http-response,pattern=^https:\/\/api\.revenuecat\.com\/v1\/subscribers.+,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/Usage.js
